version: '3'

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    restart: always
    depends_on:
      - wordpress
    ports:
      - 443:443
    volumes:
      - wp:/var/www/html
    networks:
      - sasori_chunk

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: always
    depends_on:
      - mariadb
    ports:
      - 9000:9000
    volumes:
      - wp:/var/www/html
    env_file:
      - .env
    networks:
      - sasori_chunk
      
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: always
    ports:
      - 3306:3306
    volumes:
      - md:/var/lib/mysql
    env_file:
      - .env
    networks:
      - sasori_chunk

  redis:
    build: ./requirements/bonus/redis
    container_name: redis
    depends_on:
      - wordpress
    restart: always
    ports:
      - 6379:6379
    networks:
      - sasori_chunk

  ftp:
    build: ./requirements/bonus/ftp
    container_name: ftp
    restart: always
    ports:
      - 21:21
      - 1024-1048:1024-1048
    volumes:
      - wp:/var/www/html
    networks:
      - sasori_chunk

  staticsite:
    build: ./requirements/bonus/staticsite
    container_name: staticsite
    restart: always
    ports:
      - 7777:7777
    networks:
      - sasori_chunk
  
  adminer:
    build: ./requirements/bonus/adminer
    container_name: adminer
    restart: always
    depends_on:
      - mariadb
    ports:
      - 8080:8080
    networks:
      - sasori_chunk
   
  service:
    build: ./requirements/bonus/service
    container_name: service
    restart: always
    ports:
      - 8977:8977
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - pr:/data
    networks:
      - sasori_chunk


# o: bind -> option bind to bind the volume to a specific path on the host machine, so that the data is persistent even if the container is removed
# means the files in the container are stored in the local folder specified, and changes made to those files are immediately visible in both the container and the local folder
volumes:
  wp:
    name: wp
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /Users/saxsori/data/wp

  md:
    name: md
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /Users/saxsori/data/md

  pr:
    name: pr
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /Users/saxsori/data/pr

# network driver enables containerized applications to communicate with each other and with external resources
# bridge is the default network driver, used to create internal network within docker host
# bridge driver creates a virtual network bridge on docker host, and containers connect to it
# each container gets an IP address on the bridge network
networks:
  sasori_chunk:
    name: sasori_chunk
    driver: bridge